AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: MyCodeBuildProject
      Source:
        Type: GITHUB
        Location: https://github.com/hitarthi1/Aws_Practice.git # Your GitHub repo URL
        GitCloneDepth: 1
        BuildSpec: "buildspec.yml"        
      Artifacts:
        Type: NO_ARTIFACTS
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:5.0
        PrivilegedMode: false
        EnvironmentVariables:
          - Name: GITHUB_TOKEN
            Value: "/github/personal-access-token"  # SSM parameter name
            Type: PARAMETER_STORE
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      SourceVersion: master  # Specify the branch (e.g., master)
      Triggers:
        Webhook: true
        FilterGroups:
          - - Type: EVENT
              Pattern: PUSH  # Trigger on push events

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - "logs:*"
                  - "s3:*"
                  - "codebuild:*"
                  - "ssm:GetParameter"  # Access SSM parameters
                Resource: "*"
              - Effect: Allow
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource: "arn:aws:secretsmanager:us-east-1:913524941566:secret:MyDemoProject-opqWY1"
              - Effect: Allow
                Action:
                  - "ssm:GetParameter"
                  - "ssm:GetParameters"
                Resource: "arn:aws:ssm:us-east-1:913524941566:parameter/github/personal-access-token"